[package]
name = "rs_uri_parse"
version = "0.1.0"
authors = ["Madani Lainani <madani.lainani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
